--!strict
-- Selected CC0 Kenney images. Text, layout and interaction stay Roblox-native.
-- Source paths, license and upload mapping: assets/exported/refresh/ui/manifest.json.
return table.freeze({
	panelHeader = "rbxassetid://128902092981876",
	keyboardE = "rbxassetid://123055941772617",
	playstationSquare = "rbxassetid://129641149173168",
	playstationTriangle = "rbxassetid://128266037534840",
	xboxX = "rbxassetid://104849639550862",
	xboxY = "rbxassetid://104884774554690",
})
